import Link from "next/link";
import { LegalPageNav } from "@/components/LegalPageNav";

export const metadata = {
  title: "Acceptable Use Policy — IntegrioChat",
};

const EFFECTIVE_DATE = "April 15, 2026";
const COMPANY = "IntegrioChat";
const CONTACT_EMAIL = "support@integriochat.com";

export default function AcceptableUsePolicyPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-100 px-6 py-4">
        <LegalPageNav />
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="mb-2 text-3xl font-bold text-gray-900">Acceptable Use Policy</h1>
        <p className="mb-10 text-sm text-gray-400">Effective date: {EFFECTIVE_DATE}</p>

        <div className="prose prose-gray max-w-none text-sm leading-relaxed text-gray-700 [&_h2]:mb-3 [&_h2]:mt-8 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-gray-900 [&_p]:mb-4 [&_ul]:mb-4 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:mb-1">

          <p>
            This Acceptable Use Policy (&ldquo;AUP&rdquo;) governs your use of the {COMPANY}
            platform and services. It supplements our{" "}
            <Link href="/tos" className="text-indigo-600 underline">Terms of Service</Link>.
            By using the Service, you agree to comply with this AUP.
          </p>

          <h2>1. Prohibited Activities</h2>
          <p>You may not use {COMPANY} to:</p>
          <ul>
            <li>Violate any applicable local, national, or international law or regulation.</li>
            <li>
              Infringe the intellectual property, privacy, or other rights of any third party.
            </li>
            <li>Harass, abuse, threaten, defame, or harm any person or group.</li>
            <li>
              Distribute malware, viruses, ransomware, or any other malicious code or content.
            </li>
            <li>
              Generate or distribute spam, phishing messages, scams, or fraudulent or
              deceptive content.
            </li>
            <li>
              Impersonate any person, organization, or entity, or misrepresent your
              affiliation with any party.
            </li>
            <li>
              Process sensitive personal data categories (health, financial, biometric,
              children&apos;s data) without appropriate legal basis and safeguards.
            </li>
            <li>
              Attempt unauthorized access to, or reverse-engineering of, the Service or
              any third-party systems.
            </li>
            <li>
              Scrape, crawl, or extract data from the Service in a manner that exceeds
              normal usage or violates our technical controls.
            </li>
            <li>
              Use the Service to facilitate illegal activities, including but not limited
              to money laundering, drug trafficking, or terrorism financing.
            </li>
            <li>
              Introduce content that sexualizes minors or promotes violence, hatred, or
              discrimination based on protected characteristics.
            </li>
            <li>
              Resell or sublicense the Service without our express written permission.
            </li>
          </ul>

          <h2>2. Chatbot Content Standards</h2>
          <p>
            Chatbots you create and deploy using {COMPANY} must comply with this AUP.
            You are responsible for all content generated by your chatbots and for
            ensuring that your end users are not exposed to prohibited content. You must
            not configure chatbots to deceive users about their AI nature if directly asked.
          </p>

          <h2>3. Enforcement</h2>
          <p>
            Violations of this AUP may result in immediate suspension or permanent
            termination of your account without prior notice and without refund. We
            reserve the right to report illegal activity to relevant authorities.
          </p>
          <p>
            We may monitor usage patterns for abuse detection but do not systematically
            read your chatbot conversation content.
          </p>

          <h2>4. Reporting Violations</h2>
          <p>
            To report a suspected violation of this AUP, please email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-600 underline">
              {CONTACT_EMAIL}
            </a>{" "}
            with details of the alleged violation.
          </p>

          <h2>5. Changes</h2>
          <p>
            We may update this AUP from time to time. Continued use of the Service
            after changes constitutes acceptance of the updated policy.
          </p>
        </div>
      </main>

      <footer className="border-t border-gray-100 py-6 text-center text-xs text-gray-400">
        <Link href="/privacy" className="hover:underline">Privacy Policy</Link>
        {" · "}
        <Link href="/tos" className="hover:underline">Terms of Service</Link>
        {" · "}
        <Link href="/cookie" className="hover:underline">Cookie Policy</Link>
        {" · "}
        <Link href="/refund" className="hover:underline">Refund Policy</Link>
        {" · "}
        © {new Date().getFullYear()} {COMPANY}
      </footer>
    </div>
  );
}
